name: Exemplo de artefato

on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron: "15 0 * * 1-6"  # Executa 15 a 15 minutos de segunda a sábado
  
env:
  FILE_NAME: hello-server

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Go code
      uses: actions/checkout@v4
    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go
    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

  upload-job-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

  upload-job-windows:
    runs-on: windows-latest
    steps:
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
          if-no-files-found: warn
          overwrite: true
